// lib/permissions.ts

export const permissions = {
  SUPER_ADMIN: [
    "MANAGE_USERS",
    "MANAGE_TEAMS",
    "MANAGE_PROGRAMS",
    "MANAGE_PAYMENTS",
    "VIEW_REPORTS",
  ],

  ADMIN: ["MANAGE_USERS", "MANAGE_TEAMS", "MANAGE_PROGRAMS", "VIEW_REPORTS"],

  COACH: ["VIEW_PLAYERS", "MARK_ATTENDANCE", "CREATE_EVALUATIONS"],

  PLAYER: ["VIEW_PROFILE"],

  PARENT: ["VIEW_CHILD"],
};
